language: python
sudo: required
dist: trusty
git:
  depth: 5
python:
  - 2.7
  - 3.5
  - 3.6
before_install:
  - travis/install_pandoc.sh
script:
  - python setup.py sdist
  - pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1` -vvv;
  - pushd /
  - python -c "import sys; import limix_genetics; sys.exit(limix_genetics.test())"
  - popd
notifications:
  email: false
deploy:
  provider: pypi
  skip_upload_docs: true
  user: dhorta
  on:
    distributions: sdist
    repo: glimix/limix-genetics
